# Change these first
owner: STDM-Group # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: "STRDM-Bot (https://github.com/STDM-Group/upptime)"

sites:
  - name: Home Page
    url: https://www.stardream.online
  - name: Blog
    url: https://blog.stardream.online
  - name: StarMedia
    url: $MISSKEY_RSS
    method: POST
  - name: StarTube
    url: https://video.lolihouse.top
  - name: StarDrive
    url: https://drive.stardream.online
  - name: Mail
    url: $MAIL_URL
  - name: Short Links
    url: https://links.stardream.online
  - name: Cambia
    url: https://cambia.stardream.online
  - name: IT-Tools
    url: https://itools.stardream.online
  - name: Twikoo API
    url: $TWIKOO_API
  - name: CF R2 Bucket
    url: $CF_R2

workflowSchedule:
  graphs: "0 */4 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.stardream.online
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Stardream's Site Status
  navbar:
    - title: Status
      href: /
    - title: TG Channel
      href: https://t.me/+pZKNS0GDs4o0YzM1
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Generated by [Upptime](https://upptime.js.org) | [Site source](https://github.com/STDM-Group/upptime)

commitMessages:
  commitAuthorName: "STRDM-Bot"
  commitAuthorEmail: "177311027+STRDM-Bot@users.noreply.github.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
