# Change these first
owner: STDM-Group # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
user-agent: "STRDM-Bot (https://github.com/STDM-Group/upptime)"

sites:
  - name: Home Page
    url: https://www.stardream.online
  - name: Blog - Main
    url: https://blog.stardream.online
  - name: Blog - Past
    url: https://nas-y-blog.stardream.online
  - name: StarEvent
    url: https://event.stardream.online
  - name: StarMedia
    url: https://social.lolihouse.top
    expectedStatusCodes:
      - 403
  - name: StarTube
    url: https://video.lolihouse.top
  - name: StarServer
    url: $STAR_SERVER
  - name: StarDrive
    url: https://drive.stardream.online
  - name: StarCloud
    url: $STAR_CLOUD
  - name: Filecodebox 
    url: https://file.stardream.online
  - name: Opengist 
    url: $OGT
  - name: StarTZ
    url: https://tz.stardream.online
  - name: StarLottery
    url: https://lottery.stardream.online
  - name: StarTBS
    url: https://tieba.stardream.online
  - name: Steam Card
    url: https://steam.stardream.online
  - name: osu!next
    url: https://osusig.stardream.online
  - name: Cambia
    url: https://cambia.stardream.online
  - name: IT-Tools
    url: https://itools.stardream.online
  - name: Blue Archive Logo Generator
    url: https://ba-logo.stardream.online
  - name: Docker Mirror
    url: https://docker.stardream.online
    expectedStatusCodes:
      - 404
  - name: Matrix
    url: https://matrix.lolihouse.top/_matrix/static/
    expectedStatusCodes:
      - 403
  - name: Mail
    url: $MAIL_URL
  - name: Short Links
    url: https://links.stardream.online
  - name: Twikoo API
    url: $TWIKOO_API
  - name: Gitcalendar API
    url: $GITCALENDAR_API
  - name: Fcircle API
    url: https://fcircle.stardream.online/all
  - name: CF R2 Bucket
    url: $CF_R2

workflowSchedule:
  graphs: "0 */4 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.stardream.online
  # baseUrl: /your-repo-name
  logoUrl: https://www.stardream.online/images/icon/favicon-STDM.webp
  name: Stardream's Site Status
  navbar:
    - title: Status
      href: /
    - title: Update - TG Channel
      href: https://t.me/STDM_Status_Update
    - title: Update - WebSite
      href: https://status-update.stardream.online
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Generated by [Upptime](https://upptime.js.org) | [Site source](https://github.com/STDM-Group/upptime)

commitMessages:
  commitAuthorName: "STRDM-Bot"
  commitAuthorEmail: "177311027+STRDM-Bot@users.noreply.github.com"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
